services:
  - type: web
    name: tib-backgammon
    env: node
    plan: free
    buildCommand: |
      cd client
      npm ci
      npm run build
      cd ../server
      npm ci

    startCommand: |
      cd server
      npm start
